[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python_netbox_api"
version = "0.2"
authors = [
    { name="shrank", email="info@murxs.ch" },
]
description = "Python class to access Netonix WISP Switch WebAPI"
requires-python = ">=3.0"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}
